#!/usr/bin/env bash
# This script displays the username, user id and home directory of
# every user listed in /etc/passwd
while read -r line
do
username=$(echo "$line" | awk -F: '{print $1}')
uid=$(echo "$line" | awk -F: '{print $3}')
home=$(echo "$line" | awk -F: '{print $6}')
echo "$username:$uid:$home"
done < /etc/passwd
