#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, displaying
# the number of occurrences ordered from greatest to lowest
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -rn
