#!/usr/bin/env bash
# Creates a PID file, handles signals, and runs indefinitely

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' INT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' TERM
trap 'rm -f /var/run/myscript.pid; exit 0' QUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
