#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a
# sleep 2 in between, and displays "I am invincible!!!" when it
# receives a SIGTERM signal instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
echo "To infinity and beyond"
sleep 2
done
